include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    directives_ordering: true
    prefer_relative_imports: true
    eol_at_end_of_file: true
    annotate_overrides: true
    prefer_single_quotes: true
    avoid_empty_else: true
