var themesJson = {
  'themes': [
    {
      'themeName': 'light',
      'mainColor': 0xFF000000,
      'secondaryColor': 0xFF000000,
      'tertiaryColor': 0xFF141414,
      'floatingBtnColor': 0xFF448AFF,
      'colorSchemeMain': 0xFF448AFF,
      'titleBig': 25.0,
      'titleMedium': 20.0,
      'titleSmall': 17.0,
      'bodyMedium': 17.0,
      'bodySmall': 15.0,
      'floatingButtonIconSize': 30.0,
      'backgroundColor': 0xFFFFFFFF,
      'canvasColor': 0xFFFFFFFF,
      'primaryColor': 0xFF000000,
      'brightness': 'light',
    },
    {
      'themeName': 'dark',
      'mainColor': 0xFFFFFFFF,
      'secondaryColor': 0xFFBEBEBE,
      'tertiaryColor': 0xFF787878,
      'floatingBtnColor': 0xFFF44336,
      'colorSchemeMain': 0xFFF44336,
      'titleBig': 25.0,
      'titleMedium': 20.0,
      'titleSmall': 17.0,
      'bodyMedium': 17.0,
      'bodySmall': 15.0,
      'backgroundColor': 0xFF1E1E1E,
      'floatingButtonIconSize': 30.0,
      'canvasColor': 0xFF1E1E1E,
      'primaryColor': 0xFFFFFFFF,
      'brightness': 'dark',
    }
  ],
};
